# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/200210231/miniRV_pipeline/miniRV_pipeline.cache/wt [current_project]
set_property parent.project_path D:/200210231/miniRV_pipeline/miniRV_pipeline.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/200210231/miniRV_pipeline/miniRV_pipeline.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/ip/prgrom/calculator.coe
read_verilog -library xil_defaultlib {
  D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/new/EXMEM.v
  D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/new/IDEX.v
  D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/new/IFID.v
  D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/new/LED_driver.v
  D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/new/MEMWB.v
  D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/new/alu.v
  D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/new/alu_adder.v
  D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/new/alu_bucket_shifter.v
  D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/new/alu_logicunit.v
  D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/new/alu_opdecode.v
  D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/new/branchcomp.v
  D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/new/bus_bridge.v
  D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/new/control.v
  D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/new/digit_driver.v
  D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/new/execute.v
  D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/new/hazard_handler.v
  D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/new/idecode.v
  D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/new/ifetch.v
  D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/new/miniRV.v
  D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/new/rsfile.v
  D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/new/sext.v
  D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/new/switch_driver.v
  D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/new/top.v
}
read_ip -quiet D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/ip/prgrom/prgrom.xci
set_property used_in_implementation false [get_files -all d:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/ip/prgrom/prgrom_ooc.xdc]

read_ip -quiet D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/ip/dram/dram.xci
set_property used_in_implementation false [get_files -all d:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/ip/dram/dram_ooc.xdc]

read_ip -quiet D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/ip/cpuclk/cpuclk.xci
set_property used_in_implementation false [get_files -all d:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/ip/cpuclk/cpuclk_board.xdc]
set_property used_in_implementation false [get_files -all d:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/ip/cpuclk/cpuclk.xdc]
set_property used_in_implementation false [get_files -all d:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/sources_1/ip/cpuclk/cpuclk_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/constrs_1/new/clock.xdc
set_property used_in_implementation false [get_files D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/constrs_1/new/clock.xdc]

read_xdc D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/constrs_1/new/pin.xdc
set_property used_in_implementation false [get_files D:/200210231/miniRV_pipeline/miniRV_pipeline.srcs/constrs_1/new/pin.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xc7a100tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
